# This is a basic workflow to help you get started with Actions

name: Get Job ID
description: "todo"
inputs:
  token:
    description: 'A Github PAT'
    required: true

runs:
  using: "composite"
  steps:

      - name: Get Current Job Log URL
        if: always()
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ inputs.token }}
          job_name: build
          per_page: 30
          
      - name: Output Current Job Log URL
        run: echo ${{ steps.jobs.outputs.html_url }}
        shell: "bash"
        
        
      - name: Fail the job
        run: exit 1
        shell: "bash"
        
      - name: print job status
        if: always()
        run: echo ${{ job.status }}
        shell: "bash"
        
      - name: print job status
        if: always()
        run: echo ${{ job.status }}
        shell: "bash"
          
          
          
          
