name: Pull Request Generator
on: [workflow_dispatch]

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install Dependencies
      run: |
            npm install
            npm ci

    - name: Bump Version
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm run release

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
          commit-message: bump version
          title: Bump version
          body: Bump version to reflect release changes
          branch: bump-version
          base: dev
          token: ${{ secrets.PR_REQUEST_TOKEN  }}
