name: Pull Request Generator
on: [workflow_dispatch]

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: create branch
      run: |
        git branch
        git checkout -b NickTest main
        git branch
 
    - name: Create commits
      run: |
          git config user.name 'Nickolas Reid'
          git config user.email 'nickreid89@users.noreply.github.com'
          touch Nick.txt
          git add .         
          git commit -m "Add untracked file during workflow"
          
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
