name: Pull Request Generator
on: [workflow_dispatch]

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: create branch
      run: |
        git branch
        git checkout -b NickTest main
        git branch
        git status
 
    - name: Create commits
      run: |
          git status
          git config user.name 'Nickolas Reid'
          git config user.email 'nickreid89@users.noreply.github.com'
          touch Nick.txt
          git add . 
          git status
          
    - name: Create or Update Pull Request

      uses: gr2m/create-or-update-pull-request-action@v1.5.1
      with:
        # Pull Request title
        title: testing
        # Branch name
        branch: NickTest
