name: Pull Request Generator
on: [workflow_dispatch]

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: create branch
      run: |
        git branch
        git checkout -b NickTest main
        git branch
        git status
 
    - name: Create commits
      run: |
          git status
          git config user.name 'Nickolas Reid'
          git config user.email 'nickreid89@users.noreply.github.com'
          touch Nick.txt
          git add . 
          git status
          
    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
          branch: 'NickTest'
          base: main
          title: 'demo for auto pr'
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} 
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} 
          body: 'This is to show automatic PR creation'
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
