name: Demo to create automatic PR

on:
  workflow_dispatch:

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
        
        
      - name: get the branch
        run: git checkout -b auto-pr-branch
        
      - name: add small change to the branch
        run: |
          echo "Lorem ipsum dolor sit amet, eros maiestatis ei mel, utroque accumsan no pri. Ne his vocent tractatos, an soluta mollis sea. Delicata persequeris ne mei, cum no commodo detracto. Eu eam habemus lucilius. Facer sonet lobortis id pri, delectus fabellas id cum. Cum ex iuvaret inermis conclusionemque." >> README.md
          git add README.md
          git commit -m "Initial commit"

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHO              
      - name: Generate File
        run: touch newFile.txt      
      - name: write to new file
        run: |
          cat > newFile.txt <<EOF
          info code info 
          info code info
          info code info
          EOF
      - name: Raise PR
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-pr-branch"
          base: main
          title: "demo for auto pr"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            This is to show automatic PR creation
          token: ${{ secrets.PR_REQUEST_TOKEN }}
          delete-branch: false
