name: Pull Request Generator
on: [workflow_dispatch]

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Create pull request
      uses: devops-infra/action-pull-request@v0.5.0
      with:
        github_token: ${{ secrets.PR_REQUEST_TOKEN }}
        title: Automatic pull request
