name: Remote Dispatch Action Initiator

on:
  push:
  repository_dispatch:
  
env:
  booleanValue: "false"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      # - name: PING - Dispatch initiating repository event
      #   if: github.event.action != 'pong'
      #   run: |
      #     curl -X POST https://api.github.com/repos/NickReid89/TestRepository/dispatches \  
      #     -H 'Accept: application/vnd.github.everest-preview+json' \
      #     -u ${{ secrets.PR_REQUEST_TOKEN }} \
      #     --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      # - name: ACK - Acknowledge pong from remote repository
      #   if: github.event.action == 'pong'
      #   run: |
      #     echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
      #     curl -X POST https://api.github.com/repos/NickReid89/TestRepository/dispatches \
      #     -H 'Accept: application/vnd.github.everest-preview+json' \   
      #     -u ${{ secrets.PR_REQUEST_TOKEN }} \
      #     --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

      # - uses: felixp8/dispatch-and-wait@v0.1.0
      #   with:
      #     owner: NickReid89
      #     repo: actions-remote-dispatch-d

      #     token: ${{ secrets.PR_REQUEST_TOKEN }}
      #     event_type: ping
      #     client_payload: '{"ref": "main"}'
      #     wait_time: 5
      #     max_time: 120

#       - name: Branch name
#         run: echo running on branch ${{ env.BRANCH_NAME }}
        
#       - uses: actions/checkout@v3
#         with:
#           ref: ${{ env.BRANCH_NAME }}

#       - uses: convictional/trigger-workflow-and-wait@v1.6.1
#         if: ${{ env.booleanValue == 'false' }}
#         with:
#           owner: NickReid89
#           repo: actions-remote-dispatch-d
#           github_token: ${{ secrets.PR_REQUEST_TOKEN }}
#           workflow_file_name: workflow_dispatch_example.yml
#           ref: main
#           wait_interval: 10
#           client_payload: '{"logLevel": "debug","tags": "false", "repository": "${{ github.repository }}","testvalue": "true"}'
#           propagate_failure: true
#           trigger_workflow: true
#           wait_workflow: true

      - uses: actions/checkout@v1
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: xmlToYaml
        with:
          path: './.github/workflows/person.xml'
          from: 'yaml'
          to: 'xml'
      - name: Print yaml2xml result
        run: echo "${{ steps.xmlToYaml.outputs.data }}"
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2yaml
        with:
          path: './.github/workflows/person.xml'
          from: 'xml'
          to: 'json'
      - name: Print json2yaml result
        run: echo "${{ steps.json2yaml.outputs.data }}"
        
        
        
