name: Remote Dispatch Action Initiator

on:
  push:
  schedule:
    - cron: '0 12 * * *'
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/NickReid89/TestRepository/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PR_REQUEST_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - name: ACK - Acknowledge pong from remote repository
        if: github.event.action == 'pong'
        run: |
          echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
          curl -X POST https://api.github.com/repos/NickReid89/TestRepository/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PR_REQUEST_TOKEN }} \
          --data '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'

      - uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: NickReid89
          repo: actions-remote-dispatch-d

          token: ${{ secrets.PR_REQUEST_TOKEN }}
          event_type: ping
          client_payload: '{"ref": "main"}'
          wait_time: 5
          max_time: 120


      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: NickReid89
          repo: actions-remote-dispatch-d
          github_token: ${{ secrets.PR_REQUEST_TOKEN }}
          workflow_file_name: ping.yml
          ref: main
          wait_interval: 10
          client_payload: '{"event_type": "ping", "client_payload": { "repository": "${{ github.event.repository.name }}" }}'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true